import Foundation
import MachOKit

extension LoadCommandType: ReadableDescriptionConvertible {
    public var readableDescription: String {
        switch self {
        case .segment: "Segment"
        case .symtab: "Symbol Table"
        case .symseg: "Symbol Segment"
        case .thread: "Thread State"
        case .unixthread: "UNIX Thread State"
        case .loadfvmlib: "Load Fixed VM Library"
        case .idfvmlib: "Fixed VM Library ID"
        case .ident: "Object Identification"
        case .fvmfile: "Fixed VM File Inclusion"
        case .prepage: "Prepage"
        case .dysymtab: "Dynamic Symbol Table"
        case .loadDylib: "Load Dynamic Library"
        case .idDylib: "Dynamic Library ID"
        case .loadDylinker: "Load Dynamic Linker"
        case .idDylinker: "Dynamic Linker ID"
        case .preboundDylib: "Prebound Dynamic Library"
        case .routines: "Initialization Routines"
        case .subFramework: "Sub-Framework"
        case .subUmbrella: "Sub-Umbrella"
        case .subClient: "Sub-Client"
        case .subLibrary: "Sub-Library"
        case .twolevelHints: "Two-Level Namespace Hints"
        case .prebindCksum: "Prebind Checksum"
        case .loadWeakDylib: "Load Weak Dynamic Library"
        case .segment64: "64-bit Segment"
        case .routines64: "64-bit Initialization Routines"
        case .uuid: "UUID"
        case .rpath: "Runpath Search Path"
        case .codeSignature: "Code Signature"
        case .segmentSplitInfo: "Segment Split Info"
        case .reexportDylib: "Re-export Dynamic Library"
        case .lazyLoadDylib: "Lazy-load Dynamic Library"
        case .encryptionInfo: "Encryption Info"
        case .dyldInfo: "Dynamic Loader Info"
        case .dyldInfoOnly: "Dynamic Loader Info (Only)"
        case .loadUpwardDylib: "Load Upward Dynamic Library"
        case .versionMinMacosx: "Minimum macOS Version"
        case .versionMinIphoneos: "Minimum iOS Version"
        case .functionStarts: "Function Starts"
        case .dyldEnvironment: "Dynamic Loader Environment"
        case .main: "Main Entry Point"
        case .dataInCode: "Data-in-Code Table"
        case .sourceVersion: "Source Version"
        case .dylibCodeSignDrs: "Code Signing DRs"
        case .encryptionInfo64: "64-bit Encryption Info"
        case .linkerOption: "Linker Options"
        case .linkerOptimizationHint: "Linker Optimization Hints"
        case .versionMinTvos: "Minimum tvOS Version"
        case .versionMinWatchos: "Minimum watchOS Version"
        case .note: "Vendor Note"
        case .buildVersion: "Build Version"
        case .dyldExportsTrie: "Exports Trie"
        case .dyldChainedFixups: "Chained Fixups"
        case .filesetEntry: "Fileset Entry"
        case .atomInfo: "Atom Info"
        case .functionVariants: "Function Variants"
        case .functionVariantFixups: "Function Variant Fixups"
        case .targetTriple: "Target Triple"
        case .aotMetadata: "AOT Metadata"
        }
    }
}
