name: ReleaseWithXcode16

on:
  workflow_dispatch:

env:
  DEVELOPER_DIR: /Applications/Xcode_16.0.app

jobs:
  build:
    name: Release
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode 16
        run: sudo xcode-select -s /Applications/Xcode_16.0.app

      - name: Install visionOS
        run: |
          sudo xcodebuild -runFirstLaunch
          sudo xcrun simctl list
          sudo xcodebuild -downloadPlatform visionOS
          sudo xcodebuild -runFirstLaunch

      - name: Build
        run: bash scripts/xcframework.sh

      - name: Check Sum
        run: |
          machokit="$(swift package compute-checksum XCFrameworks/MachOKit.xcframework.zip)"
          machokitc="$(swift package compute-checksum XCFrameworks/MachOKitC.xcframework.zip)"
          echo "machokit_checksum=$machokit" >> $GITHUB_ENV
          echo "machokitc_checksum=$machokitc" >> $GITHUB_ENV
          echo "MachOKit $machokit"
          echo "MachOKitC $machokitc"
